### ISSUE TITLE
Single file update

### ISSUE THREAD

**Issue by AllKinds** [meateam/project#26]
There need to be an API method for single file update that will return an error status code and an error message in case of failing to update the file.

There is already the `PUT /files/:fileId` route in the API. So the tasks are:
- [ ] Add a `UpdateFile` function to the _file-service_.
- [ ] Use this function with the route above in the _API-Gateway_.
- [ ] Verify that the UI displays an error of file-upload when there is one.

**Comment by omrishtam** [comment]
Why tho?

**Comment by AllKinds** [comment]
The user should have an indention of the cause of an update failure in case there is one.

**Comment by Shahar-Y** [comment]
So... decided on closing? 
We'll change the return value of multiple updates accordingly, yes?
