### ISSUE TITLE
Create a release version of the project

### ISSUE THREAD

**Issue by AllKinds** [meateam/project#35]
Create a stable version of the project for production.

Merge the relevant services' branches to the master branch and create a tag (v.1.2).

- [x] API
- [x] authentication
- [x] delegation
- [x] download
- [x] file
- [x] permission
- [x] permit
- [x] search
- [x] spike
- [x] upload
- [x] user
- [x] web-ui

**Comment by Shahar-Y** [comment]
Version 1.2 released on all services! :1st_place_medal:
